// <auto-generated />
using System;
using LuminaVault.GeocodingService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LuminaVault.GeocodingService.Migrations
{
    [DbContext(typeof(GeocodingDbContext))]
    partial class GeocodingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LuminaVault.GeocodingService.GeocodingCacheEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LatitudeRounded")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .HasColumnType("text");

                    b.Property<double>("LongitudeRounded")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LatitudeRounded", "LongitudeRounded")
                        .IsUnique();

                    b.ToTable("GeocodingCache");
                });
#pragma warning restore 612, 618
        }
    }
}
