// <auto-generated />
using System;
using LuminaVault.MetadataStorage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LuminaVault.MetadataStorage.Migrations
{
    [DbContext(typeof(MetadataDbContext))]
    [Migration("20260421075309_AddImportFieldsToMediaMetadata")]
    partial class AddImportFieldsToMediaMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LuminaVault.MetadataStorage.Face", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BboxHeight")
                        .HasColumnType("double precision");

                    b.Property<double>("BboxWidth")
                        .HasColumnType("double precision");

                    b.Property<double>("BboxX")
                        .HasColumnType("double precision");

                    b.Property<double>("BboxY")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaceDescription")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("Faces");
                });

            modelBuilder.Entity("LuminaVault.MetadataStorage.MediaMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<double?>("GpsLatitude")
                        .HasColumnType("double precision");

                    b.Property<string>("GpsLocation")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double?>("GpsLongitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("PersonCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MediaMetadata");
                });
#pragma warning restore 612, 618
        }
    }
}
